### ISSUE TITLE
7zipsharp has an error and won't let me activate mods

### ISSUE THREAD

**Issue by Killerdog1811** [squid-box/SevenZipSharp#33] opened 2019-02-04 16:21 UTC
I've tried looking on this site for help but no one has the same issue. Can I get some help to fix this issue as its happening to both my Fallout 4 and Skyrim SE mods?

**Comment by squid-box** [comment] 2019-02-04 17:18
I can try to help.

Give me some more info (logs, screenshots, etc) about what's happening, and which mods you're having this problem with.

Also include which version of NMM you're using.

**Comment by Killerdog1811** [comment] 2019-02-04 17:48
I'm using the newest NMM (0.65.11)
![image](https://user-images.githubusercontent.com/47328883/52226436-d1bbbc80-28a4-11e9-87df-03d22a866574.png) This is the error that shows up after i start the activation. The two ones I've had a problem with are CBBE for Fallout 4 and Remodeled armour for CBBE SSE.

**Comment by squid-box** [comment] 2019-02-04 19:01
Just to double check, is it possible that you are out of space on your hard drive? Either on the disk where your games are installed, or where your temp folder is placed (default is on `C:\`)?

**Comment by squid-box** [comment] 2019-02-06 07:00
So it's not a solution, but it's a way for me to get more info. I've built a new version of NMM with a version of SevenZipSharp that has better error logging. Could you install that and try to do the same and let me know which error code you get?

The NMM branch is [here](https://github.com/squid-box/Nexus-Mod-Manager/commits/sz_debug), and you can get a [built installer here](https://build.ahlgren.io/viewLog.html?buildId=322&buildTypeId=GitHub_Nmm_Build&tab=artifacts) (log in as guest).

**Comment by Killerdog1811** [comment] 2019-02-06 18:09
Downloaded it and extracted as it recommended. I tried opening it and it said "Windows cannot access the specified device, path or file. You may not have the appropriate permissions to access the item". And then it doesn't allow me to access it and says it everytime.

**Comment by Killerdog1811** [comment] 2019-02-06 18:24
Ok I've activated the mod again and it came up with the same error but when i moved the temp thing it made it work and im having no 7zipsharp issues.

**Comment by squid-box** [comment] 2019-02-06 22:31
Just to help me understand, you've changed the temp directory used by NMM and now the problem is no longer occurring?

**Comment by Killerdog1811** [comment] 2019-02-07 16:05
Yes i changed it and am no longer having 7zipsharp related issues.

**Comment by squid-box** [comment] 2019-02-07 17:25
Alright, thanks! I'll close the issue, reopen it if it happens again and see if you can find the error code through my test version.

**Comment by Killerdog1811** [comment] 2019-02-09 19:08
Ok had the problem again after it seemed fixed and its coming up with the same error after i activate the mod.

**Comment by squid-box** [comment] 2019-02-09 23:52
With the version I provided, are you getting an error code in the error message?

**Comment by Killerdog1811** [comment] 2019-02-10 15:55
Yes same as before with new mods that I tried to activate

**Comment by squid-box** [comment] 2019-02-10 20:24
OK, so while that is at least something, I'm not sure it helps either of us... That error code appears to point to [SHARING_VIOLATION](https://windows-hexerror.linestarve.com/0x80070020) (file being used by another process) - But it makes no sense to me why this would happen with only a select few mods.

**Comment by Killerdog1811** [comment] 2019-02-10 20:48
Yes I thought the same thing.

**Comment by Killerdog1811** [comment] 2019-02-12 20:10
Is that a no then?

**Comment by squid-box** [comment] 2019-02-12 21:42
Sorry for the silence - I have no immediate solution for you, no. I cannot reproduce the issue on my computer so it's very hard to find a way to proceed :(

Grasping at straws, the only thing I can suggest is that maybe your antivirus is locking the files while they're being unpacked. If you've already tried disabling that (or don't even have one) I don't know what else to try.

**Comment by Killerdog1811** [comment] 2019-02-13 15:29
No problem it was worth the wait cause turns out my avg was to do with it so thank you. I am no longer having 7zipsharp issues.

**Comment by squid-box** [comment] 2019-02-13 16:12
Great to hear, that means I have a reasonable troubleshooting step if this happens again :)

Closing the issue, as previously let me know if it comes back and I'll at least reopen the issue.

**Closed by squid-box** 2019-02-13 16:12 UTC

**Comment by Killerdog1811** [comment] 2019-02-13 17:04
Okay again the problem started up and all my mods are having the problem now. I think its unfixable so there's no need to worry anymore.
