### ISSUE TITLE
SevenZipExtractor exception when attempting to read from a .zip archive.

### ISSUE THREAD

**Issue by metherul** [squid-box/SevenZipSharp#68] opened 2019-10-22 19:17 UTC
```
SevenZip.SevenZipArchiveException: 'Invalid archive: open/read error! Is it encrypted and a wrong password was provided?
If your archive is an exotic one, it is possible that SevenZipSharp has no signature for its format and thus decided it is TAR by mistake.'
```

This error has been consistently reproduced in 3 different .zip archives. Not sure what to make of this. The files are not password protected, not corrupted and are not locked by another process.

**Comment by squid-box** [comment] 2019-11-22 20:21
Sorry for the month-long silence, are you able to provide either of the failing archives for me to debug? Are you able to open them in 7z, or another archive manager?

**Comment by Witherking25** [comment] 2021-02-11 20:14
i get this too

**Comment by Witherking25** [comment] 2021-02-11 20:18
it happens with all zips

**Comment by squid-box** [comment] 2021-03-05 00:10
@Witherking25

* Are you able to open them in 7z, or another archive manager?
* What version of 7z dll are you using? 
* Can you provide me with one such archive, so I can reproduce and debug the issue?

**Comment by Witherking25** [comment] 2021-03-05 00:13
They are valid zips all of them and I’m using the SevenZipSharp Interop 19.0.1 nupkg from visual studio. don’t know the version of the dll it has

**Comment by Witherking25** [comment] 2021-03-05 00:14
It happens with all zips and they work fine in all other applications even the system.io.compression library

**Comment by Witherking25** [comment] 2021-03-05 00:17
![image](https://user-images.githubusercontent.com/39203202/110048665-e71aa380-7d15-11eb-8b00-d4577a080b22.png)

**Comment by Witherking25** [comment] 2021-03-05 00:18
[7z.zip](https://github.com/squid-box/SevenZipSharp/files/6087331/7z.zip)

**Comment by Witherking25** [comment] 2021-03-05 00:22
the zip i was using is over github's size limit for uploading so it won't let me.

**Comment by Witherking25** [comment] 2021-03-05 00:23
i guess try with the one that has the dll bc it will probably have the same issue

**Comment by squid-box** [comment] 2021-03-05 19:11
@Witherking25 : Well, that makes the problem obvious at least :)

You've got `7za.dll` in there, which only supports the 7z file format - if you want support for zip (and all the others) you'll need the full 7z.dll instead.

The full 7z dll is (for 19.00) 1640KB, while the 7za dll variant is only 263KB.

**Comment by squid-box** [comment] 2021-03-05 19:13
@metherul: Since it's been a hot minute since you reported this I assume you found either the solution, or an alternative to this problem. I'll close the issue, but please reopen it with some more info if you're still seeing the problem with the full 7z.dll file.

**Closed by squid-box** 2021-03-05 19:13 UTC

**Comment by derplordofdeath** [comment] 2022-09-27 10:51
how do you fix this????

**Comment by radimbrixi** [comment] 2023-02-03 15:46
How is it fixed? It does not work also for other people

**Comment by radimbrixi** [comment] 2023-02-03 16:26
it works with old dll only like 9.38, but new dlls do not work please fix this problem.

**Comment by radimbrixi** [comment] 2023-02-03 16:27
@squid-box pls
