### ISSUE TITLE
Extraction to UNC path fails

### ISSUE THREAD

**Issue by kborowinski** [squid-box/SevenZipSharp#89] opened 2020-03-09 16:25 UTC
When extracting an archive to UNC path library fails with following error:
```
System.ArgumentException: The UNC path should be of the form \\server\share.
at SevenZip.SevenZipBase.ThrowException(CallbackBase handler, Exception[] e)
at SevenZip.SevenZipBase.CheckedExecute(Int32 hresult, String message, CallbackBase handler)
at SevenZip.SevenZipExtractor.ExtractArchive(String directory)
at SevenZip4PowerShell.Expand7Zip.ExpandWorker.Execute()
at SevenZip4PowerShell.ThreadedCmdlet.<>c__DisplayClass3_0.<StartBackgroundThread>b__0()
```

*Notes:*
1. Tested on *Squid-Box.SevenZipSharp* **1.2.258** nuget package
2. It works with original *tomap/SevenZipSharp* **1.0.19** nuget package
3. The archive is on local drive, the UNC path is valid and accessible (full read/write permission to share).

**Comment by squid-box** [comment] 2020-03-09 20:17
I've confirmed it's a problem, but the code where this happens hasn't really been touched since Tomap's version so I have no quick solution.

I'll dig into this a little, could be an easy fix.

**Comment by squid-box** [comment] 2020-03-09 20:32
The problem lies in how the destination path is validated - when trying to ensure the full path exists, SevenZipSharp was going through the path part by part:
1. Checking if the path `\` exists (it does).
2. Checking if the path `\\localhost` (does not / is not a directory).
3. Try to create the "directory" `\\localhost`, which fails with the ArgumentException you pasted.

I'll push a fix and it should be released within a few days.

**Closed** 2020-03-11 07:11 UTC
Labels: bug
